fix: AttributeError
Fies Error: AttributeError: type object 'ExtendedCashCtrlLedger' has no attribute '_assets_as_dict_of_df'

Reason: `LedgerEngine._assets_as_dict_of_df` has been renamed to `_assets_as_df` in macxred/pyledger commit 4f758b3571.